default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: papyrus_development

test:
  <<: *default
  database: papyrus_test

production:
  <<: *default
  database: papyrus_production
  username: papyrus
  password: <%= ENV["PAPYRUS_DATABASE_PASSWORD"] %>
